services:
  platform:
    build:
      network: host
      args:
        DEV_TOOLS: "1"
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command:
      - sh
      - -lc
      - |
          python manage.py migrate && \
          python -m watchfiles \
            --target-type=command \
            --filter=apps.platform.config.watchers.PythonAndHTMLFilter \
            --ignore-paths=/opt/venv \
            --ignore-paths=/app/storage \
            --ignore-paths=/app/celerybeat-schedule \
            --grace-period=0.2 \
            "daphne -b 0.0.0.0 -p 8000 apps.platform.config.asgi:application" /app
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/pyproject.toml
          action: rebuild
        - path: apps/platform/uv.lock
          action: rebuild

  platform_worker:
    build:
      network: host
      args:
        DEV_TOOLS: "1"
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command:
      - sh
      - -c
      - celery -A apps.platform.config.celery worker -l info
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/pyproject.toml
          action: rebuild
        - path: apps/platform/uv.lock
          action: rebuild

  platform_beat:
    build:
      network: host
      args:
        DEV_TOOLS: "1"
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command:
      - sh
      - -c
      - celery -A apps.platform.config.celery beat -l info
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/pyproject.toml
          action: rebuild
        - path: apps/platform/uv.lock
          action: rebuild
