services:
  platform:
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command: "sh -lc \"python -m pip install -q --no-input watchfiles && python manage.py migrate && python -m watchfiles --target-type=command --filter=apps.platform.config.watchers.PythonAndHTMLFilter --ignore-paths=/app/.venv --ignore-paths=/app/storage --ignore-paths=/app/celerybeat-schedule --grace-period=0.2 'daphne -b 0.0.0.0 -p 8000 apps.platform.config.asgi:application' /app\""
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/requirements.txt
          action: rebuild
        - path: packages/udocket_core/requirements.txt
          action: rebuild

  platform_worker:
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command: sh -lc "python -m pip install -q --no-input watchfiles && celery -A apps.platform.config.celery worker -l info"
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/requirements.txt
          action: rebuild
        - path: packages/udocket_core/requirements.txt
          action: rebuild

  platform_beat:
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: apps.platform.config.settings.dev
      CELERY_TASK_ALWAYS_EAGER: "0"
    command: sh -lc "celery -A apps.platform.config.celery beat -l info"
    develop:
      watch:
        - path: infra/docker/Dockerfile.platform
          action: rebuild
        - path: apps/platform/requirements.txt
          action: rebuild
        - path: packages/udocket_core/requirements.txt
          action: rebuild
