#!/usr/bin/env python3
"""Synchronise generated documentation assets (Mermaid diagrams, etc.)."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from collections.abc import Iterable, Sequence

from doc_tools.config import paths
from doc_tools import render_mermaid


def _expected_outputs(sources: Sequence[Path], base_dir: Path) -> list[Path]:
    outputs: list[Path] = []
    seen: set[Path] = set()
    for source in sources:
        rel = render_mermaid.build_output_relative(source, paths.DOCS_ROOT).with_suffix(".svg")
        output = base_dir / rel
        if output not in seen:
            outputs.append(output)
            seen.add(output)
    return outputs


def _manifest_state(files: Iterable[Path]) -> tuple[list[Path], list[Path]]:
    missing: list[Path] = []
    zero: list[Path] = []
    for path in files:
        if not path.exists():
            missing.append(path)
            continue
        try:
            if path.stat().st_size == 0:
                zero.append(path)
        except OSError:
            missing.append(path)
    return missing, zero


def _report_manifest(label: str, missing: Sequence[Path], zero: Sequence[Path]) -> bool:
    if not missing and not zero:
        return True
    if missing:
        print(f"[sync-doc-assets] Missing {label} files:")
        for path in missing:
            print(f"  - {path}")
    if zero:
        print(f"[sync-doc-assets] Zero-byte {label} files:")
        for path in zero:
            print(f"  - {path}")
    return False


def _run_render(mode: str, diff_base: str, out_dir: Path, verbose: bool) -> bool:
    argv: list[str] = ["--out-dir", str(out_dir)]
    if mode == "all":
        argv.insert(0, "--all")
    elif mode == "changed":
        argv[:0] = ["--changed", "--diff-base", diff_base]
    else:
        raise ValueError(f"Unknown render mode '{mode}'")
    if verbose:
        argv.append("--verbose")
    return render_mermaid.main(argv) == 0


def _format_rel(path: Path) -> str:
    try:
        return str(path.relative_to(paths.REPO_ROOT))
    except ValueError:
        return str(path)


def _log_render_plan(label: str, sources: Sequence[Path], *, limit: int | None = None, verbose: bool = False) -> None:
    total = len(sources)
    print(f"[sync-doc-assets] {label}: {total} diagram(s)")
    if not sources:
        return
    if verbose or limit is None:
        display = sources
    else:
        display = sources[:limit]
    for path in display:
        print(f"  - {_format_rel(path)}")
    if not verbose and limit is not None and total > limit:
        print(f"  ... ({total - limit} more)")


def copy_tree(src: Path, dest: Path, *, dry_run: bool) -> bool:
    if not src.exists():
        print(f"[sync-doc-assets] source directory missing: {src}")
        return False
    if dry_run:
        print(f"[sync-doc-assets] would mirror {src} -> {dest}")
        return True
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    print(f"[sync-doc-assets] mirrored {src} -> {dest}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Synchronise docs assets generated by build tooling.")
    parser.add_argument("--dry-run", action="store_true", help="Report actions without writing to disk.")
    parser.add_argument(
        "--diff-base",
        default=render_mermaid.DEFAULT_DIFF_BASE,
        help="Git reference used to detect changed diagrams",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=paths.BUILD_ROOT / "diagrams",
        help="Directory containing rendered diagrams",
    )
    parser.add_argument(
        "--destination",
        type=Path,
        default=paths.DOCS_ROOT / "build" / "diagrams",
        help="Destination directory inside the docs tree",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print per-diagram render diagnostics",
    )
    args = parser.parse_args(argv)

    render_dir = args.source
    plan_limit = None if args.verbose else 20
    dest_dir = args.destination
    all_sources = render_mermaid.collect_sources("all", paths.REPO_ROOT, paths.DOCS_ROOT, args.diff_base, [])
    expected_render_all = _expected_outputs(all_sources, render_dir)
    expected_dest_all = _expected_outputs(all_sources, dest_dir)
    missing_render, zero_render = _manifest_state(expected_render_all)
    bootstrap_needed = bool(missing_render or zero_render)
    changed_sources: list[Path] = []
    if not bootstrap_needed:
        changed_sources = render_mermaid.collect_sources("changed", paths.REPO_ROOT, paths.DOCS_ROOT, args.diff_base, [])

    if args.dry_run:
        print("[sync-doc-assets] dry-run mode")
        if bootstrap_needed:
            print("[sync-doc-assets] would run bootstrap render (--all)")
            _log_render_plan(
                "Bootstrap render targets",
                all_sources,
                limit=plan_limit,
                verbose=args.verbose,
            )
        elif changed_sources:
            print(f"[sync-doc-assets] would render {len(changed_sources)} changed diagram(s) (--changed --diff-base {args.diff_base})")
            _log_render_plan("Changed diagrams", changed_sources, limit=plan_limit, verbose=args.verbose)
        else:
            print("[sync-doc-assets] no diagram sources changed; render skipped")
        _report_manifest("render cache", missing_render, zero_render)
        missing_dest, zero_dest = _manifest_state(expected_dest_all)
        _report_manifest("docs/build mirror", missing_dest, zero_dest)
        print(f"[sync-doc-assets] would mirror {render_dir} -> {dest_dir}")
        return 0

    render_dir.mkdir(parents=True, exist_ok=True)

    if bootstrap_needed:
        print("[sync-doc-assets] Bootstrap render: generating full diagram set...")
        _log_render_plan("Bootstrap render targets", all_sources, limit=plan_limit, verbose=args.verbose)
        if not _run_render("all", args.diff_base, render_dir, args.verbose):
            return 1
    elif changed_sources:
        print(f"[sync-doc-assets] Rendering {len(changed_sources)} changed diagram(s)...")
        _log_render_plan("Changed diagrams", changed_sources, limit=plan_limit, verbose=args.verbose)
        if not _run_render("changed", args.diff_base, render_dir, args.verbose):
            return 1
    else:
        print("[sync-doc-assets] No diagram sources changed; render skipped.")

    missing_render, zero_render = _manifest_state(expected_render_all)
    if not _report_manifest("render cache", missing_render, zero_render):
        print("[sync-doc-assets] Render cache validation failed after render.")
        return 1

    if not copy_tree(render_dir, dest_dir, dry_run=False):
        return 1

    missing_dest, zero_dest = _manifest_state(expected_dest_all)
    if not _report_manifest("docs/build mirror", missing_dest, zero_dest):
        print("[sync-doc-assets] Destination validation failed after mirror.")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
