# pyright: reportUnusedImport=false, reportUnusedClass=false, reportUnusedFunction=false, reportUnusedVariable=false
# mypy: ignore-errors

from __future__ import annotations

from typing import Mapping, Protocol

__all__ = ["ChannelLayerProtocol", "SyncChannelLayerProtocol", "get_channel_layer"]

class ChannelLayerProtocol(Protocol):
    async def group_send(self, group: str, message: Mapping[str, object]) -> None: ...
    async def group_add(self, group: str, channel: str) -> None: ...
    async def group_discard(self, group: str, channel: str) -> None: ...

class SyncChannelLayerProtocol(Protocol):
    def group_send(self, group: str, message: Mapping[str, object]) -> None: ...
    def group_add(self, group: str, channel: str) -> None: ...
    def group_discard(self, group: str, channel: str) -> None: ...

def get_channel_layer() -> SyncChannelLayerProtocol | ChannelLayerProtocol | None: ...
