# Generated by Django 4.2.24 on 2025-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casemembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casemembership",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
