# Generated by Django 4.2.24 on 2025-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_historicalcase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcase",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical case",
                "verbose_name_plural": "historical cases",
            },
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="id",
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
