# Generated by Django 4.2.24 on 2025-09-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("cases", "0005_alter_historicalcase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
    ]
