# Generated by Django 4.2.24 on 2025-09-20 22:37

from django.db import migrations, models
import django.db.models.deletion


def ensure_case_organization(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    Case = apps.get_model("cases", "Case")
    db = schema_editor.connection.alias
    default_id = "default"
    org, _ = Organization.objects.using(db).get_or_create(
        id=default_id,
        defaults={"name": "Default Organization"},
    )
    Case.objects.using(db).filter(organization__isnull=True).update(organization=org)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("cases", "0006_case_organization_historicalcase_organization"),
    ]

    operations = [
        migrations.RunPython(ensure_case_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="case",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="accounts.organization",
            ),
        ),
    ]
