# Generated by Django 4.2.24 on 2025-09-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_alter_case_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("REVIEWER", "Reviewer"),
                    ("AUDITOR", "Auditor"),
                    ("EXTERNAL", "External"),
                    ("CLIENT", "Client"),
                ],
                default="CONTRIBUTOR",
                max_length=16,
            ),
        ),
    ]
