from __future__ import annotations

from typing import Any, Protocol

class _Graph(Protocol):
    def add_node(self, name: str, handler: Any) -> None: ...
    def add_edge(self, start: str, end: str) -> None: ...

class StateGraph:
    def __init__(self, state_type: Any) -> None: ...
    def add_node(self, name: str, handler: Any) -> None: ...
    def add_edge(self, start: str, end: str) -> None: ...
    def compile(self) -> _Graph: ...

START: str
END: str
