from __future__ import annotations

"""Public surface for the ai package."""

from .api import (
    AIClient,
    ChatMessage,
    ChatRequest,
    ChatResult,
    ComposeAudience,
    ComposeRequest,
    ComposeResult,
    EmbeddingRequest,
    EmbeddingResult,
    EmbeddingVector,
    EntityExtractionRequest,
    EntityExtractionResult,
    EntityHint,
    SummarizeRequest,
    SummarizeResult,
    TimelineEvent,
    TimelineExtractionRequest,
    TimelineExtractionResult,
    chat,
    compose,
    embed,
    extract_entities,
    extract_timeline,
    summarize,
)
from .config import AISettings, CapabilityLimit, ModelRoute, ProviderAccount
from .types import AgentTask, CaseContext, LanguageCode

__all__ = [
    "AIClient",
    "AISettings",
    "AgentTask",
    "CapabilityLimit",
    "CaseContext",
    "ChatMessage",
    "ChatRequest",
    "ChatResult",
    "ComposeAudience",
    "ComposeRequest",
    "ComposeResult",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EmbeddingVector",
    "EntityExtractionRequest",
    "EntityExtractionResult",
    "EntityHint",
    "LanguageCode",
    "ModelRoute",
    "ProviderAccount",
    "SummarizeRequest",
    "SummarizeResult",
    "TimelineEvent",
    "TimelineExtractionRequest",
    "TimelineExtractionResult",
    "chat",
    "compose",
    "embed",
    "extract_entities",
    "extract_timeline",
    "summarize",
]
