# Generated by Django 4.2.24 on 2025-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=128)),
                ("case_id", models.CharField(blank=True, max_length=36)),
                ("event", models.CharField(max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=200)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("job_id", models.CharField(blank=True, max_length=36)),
                ("case_id", models.CharField(blank=True, max_length=36)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
