# Generated by Django 4.2.25 on 2025-10-08 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=128)),
                ("case_id", models.CharField(blank=True, max_length=36)),
                ("event", models.CharField(max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="GuardianSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("instructions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian Settings",
                "verbose_name_plural": "Guardian Settings",
            },
        ),
        migrations.CreateModel(
            name="LLMProviderCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("provider", models.CharField(max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("models_payload", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_provider_credentials",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider")},
            },
        ),
        migrations.CreateModel(
            name="LLMConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("target", models.CharField(default="summary", max_length=64)),
                ("provider_chain", models.JSONField(blank=True, default=list)),
                ("stage_map", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configurations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "name", "target")},
            },
        ),
    ]
