# Generated by Django 4.2.24 on 2025-09-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProviderSetting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stage_key", models.CharField(max_length=128)),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("fallbacks", models.JSONField(blank=True, default=list)),
                ("allow_local_fallback", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_provider_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "stage_key")},
            },
        ),
    ]
