# Generated by Django 4.2.24 on 2025-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="task_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
