# Generated by Django 4.2.24 on 2025-09-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("operations", "0002_llmprovidersetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProviderCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("models_payload", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_provider_credentials",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider")},
            },
        ),
    ]
