# Generated by Django 4.2.24 on 2025-09-30 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_remove_llmprovidersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovidercredential",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="llmconfiguration",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
