# Generated by Codex CLI

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_merge_llmcredential_branches"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("instructions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="guardian_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
