# Generated by Django 4.2.24 on 2025-10-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_remove_taskrun"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardiansettings",
            options={
                "verbose_name": "Guardian Settings",
                "verbose_name_plural": "Guardian Settings",
            },
        ),
    ]
