from __future__ import annotations

from typing import Any, Iterable, Optional, Protocol, Sequence, Type, TypeVar, overload

T = TypeVar("T", bound="Model")
S = TypeVar("S")


class QuerySet(Sequence[T]):
    def __iter__(self) -> Iterable[T]: ...

    def all(self: "QuerySet[T]") -> "QuerySet[T]": ...

    def filter(self: "QuerySet[T]", *args: Any, **kwargs: Any) -> "QuerySet[T]": ...

    def exclude(self: "QuerySet[T]", *args: Any, **kwargs: Any) -> "QuerySet[T]": ...

    def select_related(self: "QuerySet[T]", *fields: str) -> "QuerySet[T]": ...

    def prefetch_related(self: "QuerySet[T]", *fields: str) -> "QuerySet[T]": ...

    def order_by(self: "QuerySet[T]", *fields: str) -> "QuerySet[T]": ...

    def values_list(self, *fields: str, flat: bool = ...) -> list[Any]: ...

    def values(self, *fields: str) -> list[dict[str, Any]]: ...

    def none(self: "QuerySet[T]") -> "QuerySet[T]": ...

    def annotate(self: "QuerySet[T]", **kwargs: Any) -> "QuerySet[T]": ...

    def get(self: "QuerySet[T]", *args: Any, **kwargs: Any) -> T: ...

    def first(self: "QuerySet[T]") -> Optional[T]: ...

    def last(self: "QuerySet[T]") -> Optional[T]: ...

    def exists(self) -> bool: ...

    def count(self) -> int: ...

    def update(self, **kwargs: Any) -> int: ...

    def delete(self) -> tuple[int, dict[str, int]]: ...


class Manager(QuerySet[T]):
    model: Type[T]

    def __init__(self, model: Type[T]) -> None: ...

    @overload
    def create(self, **kwargs: Any) -> T: ...

    @overload
    def create(self, **kwargs: Any) -> T: ...

    def get_queryset(self) -> QuerySet[T]: ...

    def get(self, *args: Any, **kwargs: Any) -> T: ...

    def filter(self, *args: Any, **kwargs: Any) -> QuerySet[T]: ...

    def all(self) -> QuerySet[T]: ...

    def first(self) -> Optional[T]: ...

    def last(self) -> Optional[T]: ...

    def create(self, **kwargs: Any) -> T: ...


class Model:
    objects: Manager["Model"]

    pk: Any

    class DoesNotExist(Exception): ...

    class MultipleObjectsReturned(Exception): ...

    def save(self, *args: Any, **kwargs: Any) -> None: ...

    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]: ...


class ForeignKey: ...

class ManyToManyField: ...

class OneToOneField: ...

class IntegerField: ...

class BooleanField: ...

class CharField: ...

class DateTimeField: ...

class JSONField: ...

class EmailField: ...

class TextField: ...

class UUIDField: ...


def ModelChoiceField(*args: Any, **kwargs: Any) -> Any: ...


__all__ = [
    "Model",
    "Manager",
    "QuerySet",
    "ForeignKey",
    "ManyToManyField",
    "OneToOneField",
    "IntegerField",
    "BooleanField",
    "CharField",
    "DateTimeField",
    "JSONField",
    "EmailField",
    "TextField",
    "UUIDField",
    "ModelChoiceField",
]
