# filename: udocket_models/enums.py
from __future__ import annotations
from enum import Enum

class CountryEnum(str, Enum):
    CA = "CA"
    US = "US"
    UNKNOWN_COUNTRY = "UNKNOWN_COUNTRY"

class LanguageEnum(str, Enum):
    en = "en"
    fr = "fr"
    UNKNOWN_LANG = "UNKNOWN_LANG"

class CourtLevelEnum(str, Enum):
    TRIAL_PROVINCIAL = "TRIAL_PROVINCIAL"
    TRIAL_SUPERIOR = "TRIAL_SUPERIOR"
    APPEAL = "APPEAL"
    SUPREME_NATIONAL = "SUPREME_NATIONAL"   # e.g., Supreme Court of Canada
    UNKNOWN_LEVEL = "UNKNOWN_LEVEL"

class CourtDivisionEnum(str, Enum):
    CIVIL = "CIVIL"
    CIVIL_CLAIMS = "CIVIL_CLAIMS"  # AB ACJ small claims
    FAMILY = "FAMILY"
    CRIMINAL = "CRIMINAL"
    YOUTH = "YOUTH"
    TRAFFIC = "TRAFFIC"
    SURROGATE = "SURROGATE"
    COMMERCIAL_LIST = "COMMERCIAL_LIST"
    APPLICATIONS = "APPLICATIONS"
    APPEALS = "APPEALS"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    BANKRUPTCY_INSOLVENCY = "BANKRUPTCY_INSOLVENCY"
    TAX = "TAX"
    IMMIGRATION = "IMMIGRATION"
    UNKNOWN_DIVISION = "UNKNOWN_DIVISION"

class CaseTypeEnum(str, Enum):
    CIVIL = "CIVIL"
    FAMILY = "FAMILY"
    CRIMINAL = "CRIMINAL"
    ADMINISTRATIVE_JUDICIAL_REVIEW = "ADMINISTRATIVE_JUDICIAL_REVIEW"
    APPEAL = "APPEAL"
    UNKNOWN_CASE_TYPE = "UNKNOWN_CASE_TYPE"

class CaseSubTypeEnum(str, Enum):
    # civil
    CONTRACT = "CONTRACT"
    TORT = "TORT"
    PROPERTY = "PROPERTY"
    INSURANCE = "INSURANCE"
    EMPLOYMENT = "EMPLOYMENT"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    CLASS_PROCEEDING = "CLASS_PROCEEDING"
    BANKRUPTCY_INSOLVENCY = "BANKRUPTCY_INSOLVENCY"
    JUDICIAL_REVIEW = "JUDICIAL_REVIEW"
    # family
    FAMILY_PARENTING = "FAMILY_PARENTING"
    FAMILY_SUPPORT = "FAMILY_SUPPORT"
    SURROGATE = "SURROGATE"
    # criminal
    CRIMINAL_INDICTABLE = "CRIMINAL_INDICTABLE"
    CRIMINAL_SUMMARY = "CRIMINAL_SUMMARY"
    # appeals
    APPEAL_CIVIL = "APPEAL_CIVIL"
    APPEAL_CRIMINAL = "APPEAL_CRIMINAL"
    UNKNOWN_SUBTYPE = "UNKNOWN_SUBTYPE"

class DocketStatusEnum(str, Enum):
    DRAFT_NOT_FILED = "DRAFT_NOT_FILED"
    FILED = "FILED"
    ACTIVE_PRE_TRIAL = "ACTIVE_PRE_TRIAL"
    TRIAL_SCHEDULED = "TRIAL_SCHEDULED"
    IN_TRIAL = "IN_TRIAL"
    RESERVED_FOR_DECISION = "RESERVED_FOR_DECISION"
    STAYED = "STAYED"
    DISCONTINUED = "DISCONTINUED"
    DISMISSED = "DISMISSED"
    JUDGMENT_ENTERED = "JUDGMENT_ENTERED"
    SETTLED_PENDING_DISMISSAL = "SETTLED_PENDING_DISMISSAL"
    APPEAL_PENDING = "APPEAL_PENDING"
    CLOSED = "CLOSED"
    UNKNOWN_STATUS = "UNKNOWN_STATUS"

class PostureEnum(str, Enum):
    PRE_FILING = "PRE_FILING"
    ACTIVE_PRE_TRIAL = "ACTIVE_PRE_TRIAL"
    TRIAL = "TRIAL"
    VERDICT_OR_JUDGMENT = "VERDICT_OR_JUDGMENT"
    APPEAL = "APPEAL"
    CLOSED = "CLOSED"
    UNKNOWN_POSTURE = "UNKNOWN_POSTURE"

class PartyRoleEnum(str, Enum):
    PLAINTIFF = "PLAINTIFF"
    DEFENDANT = "DEFENDANT"
    APPLICANT = "APPLICANT"
    RESPONDENT = "RESPONDENT"
    APPELLANT = "APPELLANT"
    RESPONDENT_ON_APPEAL = "RESPONDENT_ON_APPEAL"
    CROWN = "CROWN"
    ACCUSED = "ACCUSED"
    THIRD_PARTY = "THIRD_PARTY"
    INTERVENOR = "INTERVENOR"
    UNKNOWN_ROLE = "UNKNOWN_ROLE"

class PartyKindEnum(str, Enum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    GOVERNMENT_ENTITY = "GOVERNMENT_ENTITY"
    UNKNOWN_KIND = "UNKNOWN_KIND"

class RepresentativeTypeEnum(str, Enum):
    COUNSEL = "COUNSEL"
    SELF_REPRESENTED = "SELF_REPRESENTED"
    AGENT = "AGENT"
    DUTY_COUNSEL = "DUTY_COUNSEL"
    UNKNOWN_REPRESENTATIVE_TYPE = "UNKNOWN_REPRESENTATIVE_TYPE"

class HearingTypeEnum(str, Enum):
    # AB trial levels and appeal (extensible)
    JUSTICE_CHAMBERS_REGULAR = "JUSTICE_CHAMBERS_REGULAR"
    JUSTICE_CHAMBERS_SPECIAL = "JUSTICE_CHAMBERS_SPECIAL"
    APPLICATIONS_JUDGE_REGULAR = "APPLICATIONS_JUDGE_REGULAR"
    APPLICATIONS_JUDGE_SPECIAL = "APPLICATIONS_JUDGE_SPECIAL"
    CIVIL_JDR = "CIVIL_JDR"
    CASE_MANAGEMENT_CONFERENCE = "CASE_MANAGEMENT_CONFERENCE"
    PRE_TRIAL_CONFERENCE = "PRE_TRIAL_CONFERENCE"
    ASSESSMENT_OF_COSTS = "ASSESSMENT_OF_COSTS"
    TRIAL_CIVIL_JUDGE_ALONE = "TRIAL_CIVIL_JUDGE_ALONE"
    TRIAL_CIVIL_JURY = "TRIAL_CIVIL_JURY"
    FAMILY_DOCKET = "FAMILY_DOCKET"
    FAMILY_SPECIAL_CHAMBERS = "FAMILY_SPECIAL_CHAMBERS"
    EICC_FAMILY = "EICC_FAMILY"
    ACJ_CIVIL_TRIAL = "ACJ_CIVIL_TRIAL"
    CRIM_FIRST_APPEARANCE = "CRIM_FIRST_APPEARANCE"
    CRIM_BAIL_HEARING = "CRIM_BAIL_HEARING"
    CRIM_DOCKET = "CRIM_DOCKET"
    CRIM_PRELIMINARY_INQUIRY = "CRIM_PRELIMINARY_INQUIRY"
    CRIM_ARRAIGNMENT = "CRIM_ARRAIGNMENT"
    TRIAL_CRIMINAL_JUDGE_ALONE = "TRIAL_CRIMINAL_JUDGE_ALONE"
    TRIAL_CRIMINAL_JURY = "TRIAL_CRIMINAL_JURY"
    CRIM_SENTENCING = "CRIM_SENTENCING"
    ABCA_APPLICATIONS_LIST = "ABCA_APPLICATIONS_LIST"
    ABCA_SINGLE_JUDGE_APPLICATION = "ABCA_SINGLE_JUDGE_APPLICATION"
    ABCA_APPEAL_HEARING = "ABCA_APPEAL_HEARING"
    # NY examples
    NY_IAS_MOTION = "NY_IAS_MOTION"
    NY_PRELIMINARY_CONFERENCE = "NY_PRELIMINARY_CONFERENCE"
    NY_COMPLIANCE_CONFERENCE = "NY_COMPLIANCE_CONFERENCE"
    NY_TRIAL = "NY_TRIAL"
    # Federal examples
    FC_MOTION = "FC_MOTION"
    FC_TRIAL = "FC_TRIAL"
    FCA_APPEAL_HEARING = "FCA_APPEAL_HEARING"
    UNKNOWN_HEARING_TYPE = "UNKNOWN_HEARING_TYPE"

class HearingStatusEnum(str, Enum):
    SCHEDULED = "SCHEDULED"
    HEARD = "HEARD"
    ADJOURNED = "ADJOURNED"
    CANCELLED = "CANCELLED"
    RESERVED = "RESERVED"
    UNKNOWN_STATUS = "UNKNOWN_STATUS"

class FilingTypeEnum(str, Enum):
    STATEMENT_OF_CLAIM = "STATEMENT_OF_CLAIM"
    STATEMENT_OF_DEFENCE = "STATEMENT_OF_DEFENCE"
    COUNTERCLAIM = "COUNTERCLAIM"
    REPLY = "REPLY"
    ORIGINATING_APPLICATION = "ORIGINATING_APPLICATION"
    APPLICATION = "APPLICATION"
    AFFIDAVIT = "AFFIDAVIT"
    AFFIDAVIT_OF_RECORDS = "AFFIDAVIT_OF_RECORDS"
    LIST_OF_RECORDS = "LIST_OF_RECORDS"
    BRIEF_OR_MEMORANDUM = "BRIEF_OR_MEMORANDUM"
    CONSENT_ORDER_SUBMISSION = "CONSENT_ORDER_SUBMISSION"
    ORDER = "ORDER"
    JUDGMENT = "JUDGMENT"
    NOTICE_OF_APPEAL = "NOTICE_OF_APPEAL"
    APPEAL_RECORD = "APPEAL_RECORD"
    FACTUM = "FACTUM"
    EXTRACTS_OF_KEY_EVIDENCE = "EXTRACTS_OF_KEY_EVIDENCE"
    BOOK_OF_AUTHORITIES = "BOOK_OF_AUTHORITIES"
    TRANSCRIPT = "TRANSCRIPT"
    SENTENCING_SUBMISSIONS = "SENTENCING_SUBMISSIONS"
    UNKNOWN_FILING = "UNKNOWN_FILING"

class OrderTypeEnum(str, Enum):
    SCHEDULING_ENDORSEMENT = "SCHEDULING_ENDORSEMENT"
    INTERIM_ORDER = "INTERIM_ORDER"
    FINAL_ORDER = "FINAL_ORDER"
    CONSENT_ORDER = "CONSENT_ORDER"
    REASONS_FOR_JUDGMENT = "REASONS_FOR_JUDGMENT"
    MINUTE_ENTRY = "MINUTE_ENTRY"
    UNKNOWN_ORDER_TYPE = "UNKNOWN_ORDER_TYPE"

class NeutralityEnum(str, Enum):
    NEUTRAL_FACT = "NEUTRAL_FACT"
    ALLEGATION_PLAINTIFF = "ALLEGATION_PLAINTIFF"
    ALLEGATION_DEFENDANT = "ALLEGATION_DEFENDANT"
    ASSERTION_CROWN = "ASSERTION_CROWN"
    ASSERTION_ACCUSED = "ASSERTION_ACCUSED"
    UNKNOWN_NEUTRALITY = "UNKNOWN_NEUTRALITY"

class EvidenceKindEnum(str, Enum):
    DOCUMENT = "DOCUMENT"
    EMAIL = "EMAIL"
    AFFIDAVIT = "AFFIDAVIT"
    PHOTOGRAPH = "PHOTOGRAPH"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    TRANSCRIPT = "TRANSCRIPT"
    REPORT = "REPORT"
    PHYSICAL = "PHYSICAL"
    COURT_FORM = "COURT_FORM"
    UNKNOWN_EVIDENCE_KIND = "UNKNOWN_EVIDENCE_KIND"

class EvidenceOriginEnum(str, Enum):
    COURT_FILED = "COURT_FILED"
    PARTY_PROVIDED = "PARTY_PROVIDED"
    THIRD_PARTY_PROVIDED = "THIRD_PARTY_PROVIDED"
    PUBLIC_RECORD = "PUBLIC_RECORD"
    UNKNOWN_ORIGIN = "UNKNOWN_ORIGIN"

class DeadlineCategoryEnum(str, Enum):
    COURT_SET = "COURT_SET"
    RULE_BASED = "RULE_BASED"
    PARTY_PROPOSED = "PARTY_PROPOSED"
    STATUTORY = "STATUTORY"
    UNKNOWN_CATEGORY = "UNKNOWN_CATEGORY"

class RuleInstrumentEnum(str, Enum):
    ALBERTA_RULES_OF_COURT_AR_124_2010 = "ALBERTA_RULES_OF_COURT_AR_124_2010"
    KB_CIVIL_PRACTICE_NOTE_1 = "KB_CIVIL_PRACTICE_NOTE_1"
    KB_COMMERCIAL_PRACTICE_NOTE_1 = "KB_COMMERCIAL_PRACTICE_NOTE_1"
    ABCA_PRACTICE_DIRECTIONS = "ABCA_PRACTICE_DIRECTIONS"
    ACJ_PRACTICE_DIRECTIONS = "ACJ_PRACTICE_DIRECTIONS"
    FEDERAL_COURTS_RULES = "FEDERAL_COURTS_RULES"
    NY_UNIFORM_RULES = "NY_UNIFORM_RULES"
    OTHER = "OTHER"

class AreaOfLawEnum(str, Enum):
    # broad taxonomy (civil)
    CONTRACT = "CONTRACT"
    TORT = "TORT"
    PROPERTY = "PROPERTY"
    REAL_ESTATE = "REAL_ESTATE"
    INSURANCE = "INSURANCE"
    EMPLOYMENT = "EMPLOYMENT"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    PRIVACY = "PRIVACY"
    DEFAMATION = "DEFAMATION"
    COMPETITION = "COMPETITION"
    BANKING_FINANCE = "BANKING_FINANCE"
    SECURITIES = "SECURITIES"
    BANKRUPTCY_INSOLVENCY = "BANKRUPTCY_INSOLVENCY"
    CLASS_ACTIONS = "CLASS_ACTIONS"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    CONSTITUTIONAL = "CONSTITUTIONAL"
    HUMAN_RIGHTS = "HUMAN_RIGHTS"
    TAX = "TAX"
    ENVIRONMENT = "ENVIRONMENT"
    CONSTRUCTION = "CONSTRUCTION"
    PRODUCTS_LIABILITY = "PRODUCTS_LIABILITY"
    PROFESSIONAL_LIABILITY = "PROFESSIONAL_LIABILITY"
    # family/youth
    FAMILY = "FAMILY"
    CHILD_PROTECTION = "CHILD_PROTECTION"
    # estates
    ESTATES = "ESTATES"
    # criminal/traffic
    CRIMINAL = "CRIMINAL"
    TRAFFIC = "TRAFFIC"
    # immigration/federal specialties
    IMMIGRATION = "IMMIGRATION"
    MARITIME = "MARITIME"
    PATENT = "PATENT"
    TRADEMARK = "TRADEMARK"
    UNKNOWN_AREA = "UNKNOWN_AREA"
