# Generated by Django 4.2.24 on 2025-09-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_address_line1_and_more"),
        ("authorization", "0004_seed_presets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="presetfieldpolicy",
            new_name="authorizati_type_f87889_idx",
            old_name="authz_pf_type_field_idx",
        ),
        migrations.RenameIndex(
            model_name="rolecapability",
            new_name="authorizati_capabil_efc8c5_idx",
            old_name="authz_capability_idx",
        ),
        migrations.AddField(
            model_name="permissionpreset",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorization_presets",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorization_roles",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="permissionpreset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permissionpreset",
            name="slug",
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterField(
            model_name="presetcapability",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="presetfieldpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="rolecapability",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionpreset",
            unique_together={("slug", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("slug", "organization")},
        ),
        migrations.AddIndex(
            model_name="presetcapability",
            index=models.Index(
                fields=["capability"], name="authorizati_capabil_5bb269_idx"
            ),
        ),
    ]
