# Generated by Django 4.2.24 on 2025-09-21 01:32

import uuid

from django.db import migrations, models


def populate_authorization_metadata(apps, schema_editor):
    Role = apps.get_model("authorization", "Role")
    PermissionPreset = apps.get_model("authorization", "PermissionPreset")
    PresetCapability = apps.get_model("authorization", "PresetCapability")
    PresetFieldPolicy = apps.get_model("authorization", "PresetFieldPolicy")
    RoleCapability = apps.get_model("authorization", "RoleCapability")

    for role in Role.objects.filter(uuid__isnull=True):
        role.uuid = uuid.uuid4()
        role.save(update_fields=["uuid"])

    for preset in PermissionPreset.objects.filter(uuid__isnull=True):
        preset.uuid = uuid.uuid4()
        preset.save(update_fields=["uuid"])

    PresetFieldPolicy.objects.filter(resource="").update(resource="ARTIFACT")
    PresetFieldPolicy.objects.filter(resource__isnull=True).update(resource="ARTIFACT")

    preset, _ = PermissionPreset.objects.get_or_create(
        name="Client Portal",
        organization=None,
        defaults={
            "description": "Client-facing access to review approved artifacts",
            "system": True,
        },
    )
    for cap in ["case.view", "artifact.view", "artifact.download"]:
        PresetCapability.objects.get_or_create(preset=preset, capability=cap)

    PresetFieldPolicy.objects.update_or_create(
        preset=preset,
        resource="ARTIFACT",
        type="SUMMARY",
        field_name="path",
        defaults={"actions": ["view", "download"]},
    )
    PresetFieldPolicy.objects.update_or_create(
        preset=preset,
        resource="ARTIFACT",
        type="TIMELINE",
        field_name="path",
        defaults={"actions": ["view", "download"]},
    )
    PresetFieldPolicy.objects.update_or_create(
        preset=preset,
        resource="CASE",
        type="CASE",
        field_name="title",
        defaults={"actions": ["view"]},
    )
    PresetFieldPolicy.objects.update_or_create(
        preset=preset,
        resource="CASE",
        type="CASE",
        field_name="created_at",
        defaults={"actions": ["view"]},
    )

    client_role, _ = Role.objects.get_or_create(
        name="Client",
        defaults={"system": True},
    )
    for cap in ["case.view", "artifact.view", "artifact.download"]:
        RoleCapability.objects.get_or_create(role=client_role, capability=cap)
    client_role.presets.set([preset])

    RoleCapability.objects.filter(role__name__iexact="Contributor", capability="case.update").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_address_line1_and_more"),
        (
            "authorization",
            "0005_rename_authz_pf_type_field_idx_authorizati_type_f87889_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionpreset",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveIndex(
            model_name="presetfieldpolicy",
            name="authorizati_type_f87889_idx",
        ),
        migrations.AlterUniqueTogether(
            name="permissionpreset",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="presetfieldpolicy",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "name")},
        ),
        migrations.AddField(
            model_name="permissionpreset",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="presetfieldpolicy",
            name="resource",
            field=models.CharField(
                choices=[("ARTIFACT", "Artifact"), ("CASE", "Case")],
                default="ARTIFACT",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="presetfieldpolicy",
            name="type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="presetfieldpolicy",
            unique_together={("preset", "resource", "type", "field_name")},
        ),
        migrations.AddIndex(
            model_name="presetfieldpolicy",
            index=models.Index(
                fields=["resource", "type", "field_name"],
                name="authorizati_resourc_f58e54_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="permissionpreset",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="role",
            name="slug",
        ),
        migrations.RunPython(populate_authorization_metadata, migrations.RunPython.noop),
    ]
