# Generated by Django 5.2.7 on 2025-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="kc_organization_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Keycloak organization identifier.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
