from typing import Any

class TagProtocol:
    def has_attr(self, name: str) -> bool: ...
    def get(self, key: str, default: Any | None = ...) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...


class BeautifulSoup:
    def __init__(self, *args, **kwargs) -> None: ...
    def find_all(self, *args, **kwargs) -> list[TagProtocol]: ...
