#!/usr/bin/env python3
"""Synchronise generated documentation assets (Mermaid diagrams, etc.)."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = ROOT / "docs" / "src"
ASSET_ROOT = SRC_ROOT / "_assets"
MERMAID_SOURCE = ROOT / "docs" / "build" / "mermaid"
MERMAID_TARGET = ASSET_ROOT / "mermaid"


def copy_tree(src: Path, dest: Path, *, dry_run: bool) -> None:
    if not src.exists():
        print(f"[sync-doc-assets] source directory missing: {src}")
        return
    if dry_run:
        print(f"[sync-doc-assets] would mirror {src} -> {dest}")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    print(f"[sync-doc-assets] mirrored {src} -> {dest}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Synchronise docs assets generated by build tooling.")
    parser.add_argument("--dry-run", action="store_true", help="Report actions without writing to disk.")
    args = parser.parse_args(argv)

    ASSET_ROOT.mkdir(parents=True, exist_ok=True)
    copy_tree(MERMAID_SOURCE, MERMAID_TARGET, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
