from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Protocol

from packages.ai.errors import ProviderNotConfiguredError
from packages.ai.types import (
    AgentTask,
    CaseContext,
    LanguageCode,
    ProviderCallMetrics,
    UUIDStr,
)


@dataclass(slots=True, frozen=True)
class TimelineEvent:
    """Normalized event emitted by timeline/timeline-seed agents."""

    uuid: UUIDStr
    label: str
    summary: str
    speaker: str | None
    start_time_s: float | None
    evidence_refs: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class EntityHint:
    """Structured entity or relationship hint."""

    uuid: UUIDStr
    name: str
    entity_type: str
    evidence_refs: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class ChatMessage:
    """Structured chat message exchanged with an AI assistant."""

    role: str
    content: str


class ComposeAudience(StrEnum):
    """Audience-specific compose lanes."""

    CLIENT = "client"
    LAWYER = "lawyer"


class ResidencyTag(StrEnum):
    US_EAST = "US-EAST"
    EU_CENTRAL = "EU-CENTRAL"


class RuntimeProfile(StrEnum):
    ANALYZE = "automation.analyze"
    COMPOSE = "automation.compose"


@dataclass(slots=True, frozen=True)
class SummarizeRequest:
    """Input payload for the summarize agent."""

    context: CaseContext
    transcript: str
    language: LanguageCode = LanguageCode.EN_CA
    include_outline: bool = True
    include_timeline_seeds: bool = True
    include_entity_hints: bool = True


@dataclass(slots=True, frozen=True)
class SummarizeResult:
    """Outputs generated by the summarize agent."""

    summary_text: str
    outline: str | None = None
    timeline_events: tuple[TimelineEvent, ...] = field(default_factory=tuple)
    entity_hints: tuple[EntityHint, ...] = field(default_factory=tuple)
    metrics: ProviderCallMetrics | None = None


@dataclass(slots=True, frozen=True)
class ComposeRequest:
    """Input payload for the compose agent."""

    context: CaseContext
    summary_text: str
    language: LanguageCode = LanguageCode.EN_CA
    targets: tuple[ComposeAudience, ...] = (
        ComposeAudience.CLIENT,
        ComposeAudience.LAWYER,
    )


@dataclass(slots=True, frozen=True)
class ComposeResult:
    """Outputs emitted by the compose agent."""

    client_markdown: str | None = None
    lawyer_markdown: str | None = None
    qa_report_markdown: str | None = None
    metrics: ProviderCallMetrics | None = None


@dataclass(slots=True, frozen=True)
class TimelineExtractionRequest:
    """Input payload for timeline extraction."""

    context: CaseContext
    transcript: str
    language: LanguageCode = LanguageCode.EN_CA


@dataclass(slots=True, frozen=True)
class TimelineExtractionResult:
    """Normalized events produced by timeline extraction."""

    events: tuple[TimelineEvent, ...]
    metrics: ProviderCallMetrics | None = None


@dataclass(slots=True, frozen=True)
class EntityExtractionRequest:
    """Input payload for entity/relationship extraction."""

    context: CaseContext
    transcript: str
    language: LanguageCode = LanguageCode.EN_CA


@dataclass(slots=True, frozen=True)
class EntityExtractionResult:
    """Entities produced by the extraction agent."""

    entities: tuple[EntityHint, ...]
    metrics: ProviderCallMetrics | None = None


@dataclass(slots=True, frozen=True)
class ChatRequest:
    """Input payload for chat-style assistants."""

    context: CaseContext
    messages: tuple[ChatMessage, ...]
    language: LanguageCode = LanguageCode.EN_CA


@dataclass(slots=True, frozen=True)
class ChatResult:
    """Chat response envelope."""

    messages: tuple[ChatMessage, ...]
    metrics: ProviderCallMetrics | None = None


@dataclass(slots=True, frozen=True)
class EmbeddingRequest:
    """Embedding job specification."""

    context: CaseContext
    inputs: tuple[str, ...]
    language: LanguageCode = LanguageCode.EN_CA
    model_hint: str | None = None


@dataclass(slots=True, frozen=True)
class EmbeddingVector:
    """Embedding vector for a single input string."""

    input_text: str
    values: tuple[float, ...]


@dataclass(slots=True, frozen=True)
class EmbeddingResult:
    """Embedding response payload."""

    vectors: tuple[EmbeddingVector, ...]
    metrics: ProviderCallMetrics | None = None


class AIClient(Protocol):
    """Protocol expected from concrete AI clients."""

    def summarize(self, request: SummarizeRequest) -> SummarizeResult: ...

    def compose(self, request: ComposeRequest) -> ComposeResult: ...

    def extract_timeline(
        self,
        request: TimelineExtractionRequest,
    ) -> TimelineExtractionResult: ...

    def extract_entities(
        self,
        request: EntityExtractionRequest,
    ) -> EntityExtractionResult: ...

    def chat(self, request: ChatRequest) -> ChatResult: ...

    def embed(self, request: EmbeddingRequest) -> EmbeddingResult: ...


def summarize(request: SummarizeRequest, *, client: AIClient | None = None) -> SummarizeResult:
    """Execute the summarize agent via the configured AI client."""
    return _require_client(client, AgentTask.GENERATE).summarize(request)


def compose(request: ComposeRequest, *, client: AIClient | None = None) -> ComposeResult:
    """Execute the compose agent and return audience-specific deliverables."""
    return _require_client(client, AgentTask.GENERATE).compose(request)


def extract_timeline(
    request: TimelineExtractionRequest,
    *,
    client: AIClient | None = None,
) -> TimelineExtractionResult:
    """Normalize timeline events based on diarized transcripts."""
    return _require_client(client, AgentTask.EXTRACT).extract_timeline(request)


def extract_entities(
    request: EntityExtractionRequest,
    *,
    client: AIClient | None = None,
) -> EntityExtractionResult:
    """Derive entity/relationship hints for downstream tooling."""
    return _require_client(client, AgentTask.EXTRACT).extract_entities(request)


def chat(request: ChatRequest, *, client: AIClient | None = None) -> ChatResult:
    """Run a chat-style assistant exchange."""
    return _require_client(client, AgentTask.CHAT).chat(request)


def embed(request: EmbeddingRequest, *, client: AIClient | None = None) -> EmbeddingResult:
    """Request embeddings for the provided inputs."""
    return _require_client(client, AgentTask.EMBED).embed(request)


def _require_client(client: AIClient | None, task: AgentTask) -> AIClient:
    if client is None:
        raise ProviderNotConfiguredError(task=task)
    return client


__all__ = [
    "AIClient",
    "ResidencyTag",
    "RuntimeProfile",
    "ChatMessage",
    "ChatRequest",
    "ChatResult",
    "ComposeAudience",
    "ComposeRequest",
    "ComposeResult",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EmbeddingVector",
    "EntityExtractionRequest",
    "EntityExtractionResult",
    "EntityHint",
    "SummarizeRequest",
    "SummarizeResult",
    "TimelineEvent",
    "TimelineExtractionRequest",
    "TimelineExtractionResult",
    "chat",
    "compose",
    "embed",
    "extract_entities",
    "extract_timeline",
    "summarize",
]
