# Generated by Django 4.2.24 on 2025-09-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseArtifact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("case_id", models.CharField(max_length=36)),
                ("job_id", models.CharField(blank=True, max_length=36, null=True)),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("path", models.TextField()),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("schema_version", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case_id", "type"],
                        name="artifacts_c_case_id_cfc414_idx",
                    )
                ],
            },
        ),
    ]
