# Generated by Django 4.2.24 on 2025-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0006_seed_visibility_rules"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql="DROP INDEX IF EXISTS artifacts_c_case_id_cfc414_idx;", reverse_sql=""),
            ],
            state_operations=[
                migrations.RemoveIndex(model_name="caseartifact", name="artifacts_c_case_id_cfc414_idx"),
            ],
        ),
        migrations.RenameIndex(
            model_name="fieldvisibilityrule",
            new_name="artifacts_f_type_8d70a5_idx",
            old_name="artv_type_field_idx",
        ),
        migrations.AlterField(
            model_name="fieldvisibilityrule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
