# Generated by Django 4.2.24 on 2025-09-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_historicalcase_options_and_more"),
        ("artifacts", "0008_historicalcaseartifact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcaseartifact",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical case artifact",
                "verbose_name_plural": "historical case artifacts",
            },
        ),
        migrations.AlterField(
            model_name="historicalcaseartifact",
            name="case_fk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcaseartifact",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
