# Generated by Django 4.2.24 on 2025-09-20 21:21

from django.db import migrations, models
import django.db.models.deletion


def backfill(apps, schema_editor):
    CaseArtifact = apps.get_model("artifacts", "CaseArtifact")
    Case = apps.get_model("cases", "Case")
    db = schema_editor.connection.alias

    # First, leverage case_fk when available (covers all current records after migration 0005)
    for pk, case_fk_id in CaseArtifact.objects.using(db).filter(
        organization__isnull=True, case_fk__isnull=False
    ).values_list("pk", "case_fk_id"):
        if not case_fk_id:
            continue
        org_id = (
            Case.objects.using(db)
            .filter(pk=case_fk_id)
            .values_list("organization_id", flat=True)
            .first()
        )
        if org_id:
            CaseArtifact.objects.using(db).filter(pk=pk).update(organization_id=org_id)

    # Some legacy rows may still lack case_fk but retain case_id. Only attempt when column exists.
    try:
        with schema_editor.connection.cursor() as cursor:
            cols = {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, CaseArtifact._meta.db_table)}
    except Exception:
        cols = set()
    if "case_id" not in cols:
        return

    for pk, case_id in CaseArtifact.objects.using(db).filter(
        organization__isnull=True, case_fk__isnull=True
    ).values_list("pk", "case_id"):
        if not case_id:
            continue
        org_id = (
            Case.objects.using(db)
            .filter(pk=case_id)
            .values_list("organization_id", flat=True)
            .first()
        )
        if org_id:
            CaseArtifact.objects.using(db).filter(pk=pk).update(organization_id=org_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("artifacts", "0009_alter_historicalcaseartifact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalcaseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.RunPython(code=backfill, reverse_code=migrations.RunPython.noop),
    ]
