# Generated by Django 4.2.24 on 2025-09-20 21:21

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("artifacts", "0009_alter_historicalcaseartifact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalcaseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
        migrations.RunPython(code="apps.platform.artifacts.migrations.0010_caseartifact_organization_and_more.backfill", reverse_code=migrations.RunPython.noop),
    ]


def backfill(apps, schema_editor):
    CaseArtifact = apps.get_model("artifacts", "CaseArtifact")
    Case = apps.get_model("cases", "Case")
    # Try to backfill via FK when present
    try:
        CaseArtifact.objects.filter(organization__isnull=True, case_fk__isnull=False).update(
            organization=F("case_fk__organization")
        )
    except Exception:
        for a in CaseArtifact.objects.filter(organization__isnull=True, case_fk__isnull=False).select_related("case_fk"):
            a.organization_id = getattr(a.case_fk, "organization_id", None)
            a.save(update_fields=["organization"])
    # For artifacts without case_fk, use case_id lookup
    for a in CaseArtifact.objects.filter(organization__isnull=True, case_fk__isnull=True).iterator():
        org_id = None
        try:
            org_id = Case.objects.filter(id=a.case_id).values_list("organization_id", flat=True).first()
        except Exception:
            pass
        if org_id:
            a.organization_id = org_id
            a.save(update_fields=["organization"])
