# Generated by Django 4.2.24 on 2025-09-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("artifacts", "0009_alter_historicalcaseartifact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalcaseartifact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.organization",
            ),
        ),
    ]
