# Generated by Django 4.2.24 on 2025-09-20 22:37

from django.db import migrations, models
import django.db.models.deletion


def backfill_artifact_org(apps, schema_editor):
    CaseArtifact = apps.get_model("artifacts", "CaseArtifact")
    Case = apps.get_model("cases", "Case")
    db = schema_editor.connection.alias
    for art in CaseArtifact.objects.using(db).filter(organization__isnull=True).iterator():
        org_id = None
        if art.case_fk_id:
            org_id = (
                Case.objects.using(db)
                .filter(pk=art.case_fk_id)
                .values_list("organization_id", flat=True)
                .first()
            )
        if org_id is None and art.case_id:
            org_id = (
                Case.objects.using(db)
                .filter(pk=art.case_id)
                .values_list("organization_id", flat=True)
                .first()
            )
        if org_id:
            CaseArtifact.objects.using(db).filter(pk=art.pk).update(organization_id=org_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("cases", "0007_alter_case_organization"),
        ("artifacts", "0010_caseartifact_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_artifact_org, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="caseartifact",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="accounts.organization",
            ),
        ),
    ]
