# Generated by Django 4.2.24 on 2025-09-21 01:32

from django.db import migrations, models


def set_default_visibility_resource(apps, schema_editor):
    Rule = apps.get_model("artifacts", "FieldVisibilityRule")
    Rule.objects.filter(resource__isnull=True).update(resource="ARTIFACT")
    Rule.objects.filter(resource="").update(resource="ARTIFACT")


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0011_alter_caseartifact_organization"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fieldvisibilityrule",
            name="artifacts_f_type_8d70a5_idx",
        ),
        migrations.AlterUniqueTogether(
            name="fieldvisibilityrule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fieldvisibilityrule",
            name="resource",
            field=models.CharField(
                choices=[("ARTIFACT", "Artifact"), ("CASE", "Case")],
                default="ARTIFACT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fieldvisibilityrule",
            name="type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="fieldvisibilityrule",
            unique_together={("resource", "type", "field_name")},
        ),
        migrations.AddIndex(
            model_name="fieldvisibilityrule",
            index=models.Index(
                fields=["resource", "type", "field_name"],
                name="artifacts_f_resourc_eb394e_idx",
            ),
        ),
        migrations.RunPython(set_default_visibility_resource, migrations.RunPython.noop),
    ]
