from __future__ import annotations

from typing import Iterable, Protocol, Sequence, Tuple


class ImageFile:
    width: int
    height: int

    def save(self, fp, format: str | None = ..., **kwargs: object) -> None: ...
    def load(self) -> None: ...
    def __enter__(self) -> ImageFile: ...
    def __exit__(self, exc_type, exc, tb) -> bool | None: ...


class ImageModule(Protocol):
    def new(self, mode: str, size: Tuple[int, int], color: object | None = ...) -> ImageFile: ...
    def open(self, fp, mode: str | None = ..., formats: Iterable[str] | None = ...) -> ImageFile: ...


class DrawContext:
    def line(self, xy: Iterable[float] | Iterable[Tuple[float, float]], fill: object | None = ..., width: int | None = ...) -> None: ...
    def polygon(self, xy: Iterable[Tuple[float, float]], fill: object | None = ..., outline: object | None = ...) -> None: ...
    def ellipse(self, xy: Sequence[float] | Sequence[Tuple[float, float]], fill: object | None = ..., outline: object | None = ..., width: int | None = ...) -> None: ...
    def rectangle(self, xy: Sequence[float] | Sequence[Tuple[float, float]], fill: object | None = ..., outline: object | None = ..., width: int | None = ...) -> None: ...
    def text(self, xy: Tuple[float, float], text: str, fill: object | None = ..., font: object | None = ...) -> None: ...


class ImageDrawModule(Protocol):
    def Draw(self, image: ImageFile) -> DrawContext: ...


class ImageFontType:
    def getbbox(self, text: str) -> tuple[int, int, int, int]: ...
    def getsize(self, text: str) -> tuple[int, int]: ...


class ImageFontModule(Protocol):
    def truetype(self, font: str, size: int, *args: object, **kwargs: object) -> ImageFontType: ...
    def load_default(self) -> ImageFontType: ...


Image: ImageModule
ImageDraw: ImageDrawModule
ImageFont: ImageFontModule
