#!/usr/bin/env python
"""Generate pip-compatible requirements exports for all uv-managed projects."""

from __future__ import annotations

import argparse
import shlex
import subprocess
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS_DIR = REPO_ROOT / "requirements"

Project = tuple[str, Path, Iterable[str | None]]

if sys.version_info < (3, 12):
    raise RuntimeError("Python 3.12 or newer is required to run export_requirements.py")

PROJECTS: tuple[Project, ...] = (
    ("platform", REPO_ROOT / "apps" / "platform", (None, "dev")),
    ("common", REPO_ROOT / "packages" / "common", (None, "dev")),
    ("core", REPO_ROOT / "packages" / "core", (None, "dev")),
    ("docs", REPO_ROOT / "packages" / "docs_tooling", (None, "dev")),
)


def run_uv_export(project: str, project_dir: Path, group: str | None) -> str:
    command = [
        "uv",
        "export",
        "--frozen",
        "--format",
        "requirements-txt",
        "--project",
        str(project_dir),
    ]
    if group:
        command.extend(["--group", group])

    proc = subprocess.run(command, check=True, capture_output=True, text=True)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lock_path = project_dir / "uv.lock"
    header_lines = [
        "# Auto-generated by uv export; do not edit.",
        f"# Project: {project}",
        f"# Environment group: {group or 'default'}",
        f"# Source lock file: {lock_path.relative_to(REPO_ROOT) if lock_path.exists() else 'N/A'}",
        f"# Generated on: {timestamp}",
        f"# Command: {' '.join(shlex.quote(part) for part in command)}",
        "",
    ]
    body = proc.stdout.strip()
    return "\n".join(header_lines + [body, ""]) if body else "\n".join(header_lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        current = path.read_text()
        if current == content:
            return False
    path.write_text(content)
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export pip-compatible requirements files.")
    parser.add_argument(
        "projects",
        nargs="*",
        metavar="project",
        help="Project slugs to export (default: all projects)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    REQUIREMENTS_DIR.mkdir(parents=True, exist_ok=True)
    valid_names = {name for name, *_ in PROJECTS}
    unknown = sorted(set(args.projects) - valid_names)
    if unknown:
        joined = ", ".join(sorted(valid_names))
        raise SystemExit(f"Unknown project(s): {', '.join(unknown)}. Valid options: {joined}.")

    selected = [entry for entry in PROJECTS if not args.projects or entry[0] in args.projects]
    for project, project_dir, groups in selected:
        if not project_dir.exists():
            continue
        for group in groups:
            suffix = "-dev" if group else ""
            output_path = REQUIREMENTS_DIR / f"{project}{suffix}.txt"
            content = run_uv_export(project, project_dir, group)
            if write_if_changed(output_path, content):
                print(f"Updated {output_path.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
