from typing import Iterable, Iterator, Mapping, Optional, Sequence, overload


class XMLParser:
    def __init__(self, *, remove_comments: bool = ...) -> None: ...


class _Element:
    tag: str
    attrib: dict[str, str]
    text: Optional[str]
    tail: Optional[str]

    def xpath(self, path: str, namespaces: Optional[Mapping[str, str]] = ...) -> Sequence["_Element"]: ...
    def find(self, path: str) -> Optional["_Element"]: ...
    def findall(self, path: str) -> Sequence["_Element"]: ...
    def get(self, key: str, default: Optional[str] = ...) -> str: ...
    def set(self, key: str, value: str) -> None: ...
    def append(self, element: "_Element") -> None: ...
    def remove(self, element: "_Element") -> None: ...
    def getparent(self) -> Optional["_Element"]: ...
    def itertext(self) -> Iterator[str]: ...
    def iterancestors(self, tag: Optional[str] = ...) -> Iterator["_Element"]: ...
    def __iter__(self) -> Iterator["_Element"]: ...
    def __getitem__(self, index: int) -> "_Element": ...
    def insert(self, index: int, element: "_Element") -> None: ...


class _ElementTree:
    def __init__(self, root: _Element) -> None: ...
    def getroot(self) -> _Element: ...


def Element(tag: str, attrib: Optional[dict[str, str]] = ..., nsmap: Optional[dict[str, str]] = ...) -> _Element: ...
def parse(source: str, parser: Optional[XMLParser] = ...) -> _ElementTree: ...

@overload
def tostring(element: _Element, encoding: str = ..., pretty_print: bool = ..., xml_declaration: bool = ...) -> str: ...

@overload
def tostring(element: _Element, encoding: bytes = ..., pretty_print: bool = ..., xml_declaration: bool = ...) -> bytes: ...
