# Generated by Django 4.2.24 on 2025-09-20 21:21

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def backfill(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    try:
        Job.objects.filter(organization__isnull=True).update(organization=F("case__organization"))
    except Exception:
        for j in Job.objects.filter(organization__isnull=True).select_related("case"):
            j.organization_id = getattr(j.case, "organization_id", None)
            j.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("jobs", "0002_add_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="accounts.organization",
            ),
        ),
        migrations.RunPython(code=backfill, reverse_code=migrations.RunPython.noop),
    ]
