# Generated by Django 4.2.24 on 2025-09-20 22:37

from django.db import migrations, models
import django.db.models.deletion


def backfill_job_org(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Case = apps.get_model("cases", "Case")
    db = schema_editor.connection.alias
    for job in Job.objects.using(db).filter(organization__isnull=True).iterator():
        org_id = (
            Case.objects.using(db)
            .filter(pk=job.case_id)
            .values_list("organization_id", flat=True)
            .first()
        )
        if org_id:
            Job.objects.using(db).filter(pk=job.pk).update(organization_id=org_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_and_membership"),
        ("cases", "0007_alter_case_organization"),
        ("jobs", "0003_job_organization"),
    ]

    operations = [
        migrations.RunPython(backfill_job_org, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="job",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="accounts.organization",
            ),
        ),
    ]
