# Generated by Django 4.2.24 on 2025-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_status_add_converting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("CONVERTING", "Converting"),
                    ("UPLOADING", "Uploading"),
                    ("CANCELLING", "Cancelling"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("CORRUPTED", "Corrupted"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
